### ISSUE TITLE
Q_Config not found

### ISSUE THREAD

**Issue by mkapur** [nwfsc-assess/VASTWestCoast#16]
This was working fine a few weeks ago, but suddently the VAST_condition() function returns an error that Q_Config not found. I sorted it for myself by specifying Q_Config <- T or F in global env.
MK

**Comment by kellijohnson-NOAA** [comment]
Closing b/c I think this is a FishStatUtils problem and I have my own fork. I am working on upgrading to the latest version of VAST and FishStatUtils which will lead to other issues and fixes. :(
