### ISSUE TITLE
spatial_list not found when using example code

### ISSUE THREAD

**Issue by mkapur** [nwfsc-assess/VASTWestCoast#18]
I'm doing some testing to ensure I get comprable results using VAST "on it's own" vs this package, e.g. what was used in the 2019 Sablefish assessment. However, when I run the following (same as example [here](https://github.com/nwfsc-assess/VASTWestCoast/blob/master/inst/examples/WCGBTS_annual_2019.R)) I get an error, which occurred both before & after a new install. Strange because I used this code for Widow earlier in the summer. Let me know if overlooking something obvious, thanks!

  ```
devtools::install_github("nwfsc-assess/VASTWestCoast")
library(VASTWestCoast)
Sim_Settings <- list(
  "Species" = "WCGBTS_Anoplopoma_fimbria",
  "ObsModelcondition" = c(2, 1),
  "nknots" = 250,
  "strata" = data.frame("STRATA" = "All_areas"),
  "depth" = c("no", "linear", "squared")[1],
  "Passcondition" = TRUE)

downloaddir <- getwd()

test <- VAST_condition(
  conditiondir = downloaddir,
  settings = Sim_Settings, spp = Sim_Settings$Species,
  datadir = downloaddir,
  overdispersion = NULL)
VAST_diagnostics(downloaddir)
```

And the error:

```
Using strata 1
convUL: For the UTM conversion, automatically detected zone 10.
convUL: Converting coordinates within the northern hemisphere.
Error in ifelse(is.null(spatial_list), 1, spatial_list$n_g) : 
  argument "spatial_list" is missing, with no default
```

**Comment by kellijohnson-NOAA** [comment]
@mkapur I think I responded to this via email rather than here, which was bad on my part. Anyway, I think this was happening because of a mismatch in FishStatsUtils versions. Please let me know if there is anything that I can help with currently.
