### ISSUE TITLE
check_TMB()

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nwfsc-assess/VASTWestCoast#32]
Thanks for adding this function and I was finally able to confirm that my TMB is now working.  However, just calling and running this function did not work on my machine.  I received this error:

'system.file' is not an exported object from 'namespace:pkgload'

However, I was able run the code in check_TMB() by line replacing this line:  

setwd(pkgload::system.file("examples", package = "TMB")) 

and setting the working directory of my TMB example folder.  I do have both devtools and pckload newly installed on my machine, so I am not entirely sure why the original line would not run.  This issue may be specific to me and my machine but I am not certain and thought flagging this may be useful in case others have similar issues.

**Comment by kellijohnson-NOAA** [comment]
Thanks @chantelwetzel-noaa . I see my mistake, there are two versions of system.file(), one in base R and one in pkgload, where the latter is a replacement for the former. I have fixed the code, I think, with ec199fb.
