### ISSUE TITLE
Latest version of VAST

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nwfsc-assess/VASTWestCoast#5]
Update to use the latest version of VAST.

**Comment by kellijohnson-NOAA** [comment]
The minimal example now works with VAST_v5_3_0, which is the most current version of VAST. Also updated the get_settings to pull out the latest version if a version isn't given and changed all examples to reflect this.

**Comment by James-Thorson** [comment]
Kelli,

In the DESCRIPTION I recommend listing VAST version >= 2.0.0 as dependency.  I also plan to start including version-number specific dependencies in my dependency on FishStatsUtils.

**Comment by kellijohnson-NOAA** [comment]
Good to know. I will do that shortly.
